Controllers/TiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoodLookTie.Data;
using GoodLookTie.Models;

namespace GoodLookTie.Controllers
{
    public class TiesController : Controller
    {
        private readonly GoodLookTieContext _context;

        public TiesController(GoodLookTieContext context)
        {
            _context = context;
        }

        // GET: Ties
        public async Task<IActionResult> Index(string tieMaterial, string searchString)
        {
            IQueryable<string> materialQuery = from m in _context.Tie
                                            orderby m.Material
                                            select m.Material;

            var ties = from m in _context.Tie
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                ties = ties.Where(s => s.Type.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(tieMaterial))
            {
                ties = ties.Where(x => x.Material == tieMaterial);
            }

            var tieMaterialVM = new TieMaterialViewModel
            {
                Material = new SelectList(await materialQuery.Distinct().ToListAsync()),
                Ties = await ties.ToListAsync()
            };

            return View(tieMaterialVM);
        }

        // GET: Ties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tie = await _context.Tie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tie == null)
            {
                return NotFound();
            }

            return View(tie);
        }

        // GET: Ties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Type,Material,Colour,Origin,Price")] Tie tie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tie);
        }

        // GET: Ties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tie = await _context.Tie.FindAsync(id);
            if (tie == null)
            {
                return NotFound();
            }
            return View(tie);
        }

        // POST: Ties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,Material,Colour,Origin,Price")] Tie tie)
        {
            if (id != tie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TieExists(tie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tie);
        }

        // GET: Ties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tie = await _context.Tie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tie == null)
            {
                return NotFound();
            }

            return View(tie);
        }

        // POST: Ties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tie = await _context.Tie.FindAsync(id);
            _context.Tie.Remove(tie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TieExists(int id)
        {
            return _context.Tie.Any(e => e.Id == id);
        }
    }
}

Views/Ties/Create.cshtml
@model GoodLookTie.Models.Tie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Material" class="control-label"></label>
                <input asp-for="Material" class="form-control" />
                <span asp-validation-for="Material" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colour" class="control-label"></label>
                <input asp-for="Colour" class="form-control" />
                <span asp-validation-for="Colour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Occassion" class="control-label"></label>
                <input asp-for="Occassion" class="form-control" />
                <span asp-validation-for="Occassion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ties/Delete.cshtml
@model GoodLookTie.Models.Tie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Ties/Details.cshtml
@model GoodLookTie.Models.Tie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Ties/Edit.cshtml
@model GoodLookTie.Models.Tie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Material" class="control-label"></label>
                <input asp-for="Material" class="form-control" />
                <span asp-validation-for="Material" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colour" class="control-label"></label>
                <input asp-for="Colour" class="form-control" />
                <span asp-validation-for="Colour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ties/Index.cshtml
@model GoodLookTie.Models.TieMaterialViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Ties" asp-action="Index" method="get">
    <p>
        <select asp-for="TieMaterial" asp-items="Model.Material">
            <option value="">All</option>
        </select>
        Type: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ties[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ties[0].Material)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ties[0].Colour)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ties[0].Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ties[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ties[0].Occassion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Ties)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Material)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Colour)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Origin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Occassion)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>